return {
  'tpope/vim-repeat',
  { 'tpope/vim-fugitive', event = "VeryLazy" },
  { 'tpope/vim-surround', event = "VeryLazy" },
  { 'tpope/vim-speeddating', event = "VeryLazy" },
  'tpope/vim-commentary',
  'tpope/vim-obsession',
  'tpope/vim-scriptease',
  'justinmk/vim-sneak',
  { 'tommcdo/vim-exchange', keys = { 'cx', 'cxx', 'cxc', { 'X', mode = 'x' } } },
  { 'wellle/targets.vim', event = "ModeChanged *:*o*" },
  { 'tommcdo/vim-lion', keys = { 'gl', 'gL' } },
  'machakann/vim-highlightedyank',
  'itchyny/vim-cursorword',
  'jeetsukumaran/vim-filebeagle',
  'inkarkat/vim-SyntaxRange',
  'mbbill/undotree',
}
